chore(storybook): add gh action deployment for storybook on gh pages

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -36,6 +36,40 @@ jobs:
                   NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
                   NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
                   NEXT_PUBLIC_REST_API: ${{ secrets.NEXT_PUBLIC_REST_API }}
+    build_docs:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Checkout
+              uses: actions/checkout@v4
+            - name: Detect package manager
+              id: detect-package-manager
+              run: |
+                  if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+                  echo "manager=yarn" >> $GITHUB_OUTPUT
+                  echo "command=install" >> $GITHUB_OUTPUT
+                  echo "runner=yarn" >> $GITHUB_OUTPUT
+                  exit 0
+                  elif [ -f "${{ github.workspace }}/package.json" ]; then
+                  echo "manager=npm" >> $GITHUB_OUTPUT
+                  echo "command=ci" >> $GITHUB_OUTPUT
+                  echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+                  exit 0
+                  else
+                  echo "Unable to determine package manager"
+                  exit 1
+                  fi
+            - name: Setup Node
+              uses: actions/setup-node@v4
+              with:
+                  node-version: '16'
+                  cache: ${{ steps.detect-package-manager.outputs.manager }}
+            - name: Deploy Storybook Docs
+              uses: bitovi/github-actions-storybook-to-github-pages@v1.0.1
+              with:
+                  install_command: yarn install # default: npm ci
+                  build_command: yarn build-storybook # default: npm run build-storybook
+                  path: storybook-static # default: dist/storybook
+                  checkout: false # default: true
     close_pull_request_job:
         if: github.event_name == 'pull_request' && github.event.action == 'closed'
         runs-on: ubuntu-latest
